### ISSUE TITLE
Cannot escape the quotes in commands

### ISSUE THREAD

**Issue by Laphae-L** [LaphaeL12304/LaphaeLaicmd-linux#3]
# 描述
无法正常的转义命令中的引号（包括双引号和单引号）。

# 复现
- 运行程序后输入`/cmd ` 加上任何带引号的命令
- 例如：`/cmd echo \"` 实际输出`\`，而应该预期输出`"`

#  环境
- Ubuntu 22.04 LTS

# 已经尝试过但没能解决的办法
1. 尝试在execute_cmd模块中转义引号，至少我没成功
2. 曾怀疑是'\'转义符缺乏转义，因此尝试把命令中的'\'替换为"\\"，没成功

**Comment by LaphaeL12304** [comment]
已在v1.2.2解决
